title: OutlinedArc217 in ğŸŒ
name: OutlinedArc217
email: z3407323905@outlook.com
description: â‚Ë„Â·Íˆà¼Â·ÍˆË„*â‚â— Ì‘Ì‘
baseurl: "/blog" 
url: "http://outlinedarc217.github.io"
github_username:  OutlinedArc217

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Libstack
    link: https://t.me/libstack
  

disqus: true
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
